import networkx as nx
import matplotlib.pyplot as plt
from textwrap import wrap

# 自动换行函数
def wrap_labels(labels, width=10):
    wrapped_labels = {}
    for key, text in labels.items():
        wrapped_labels[key] = '\n'.join(wrap(text, width))
    return wrapped_labels

# 定义triples列表
"""
triples = [
    ["evaluation criterion", "used for", "word similarity measures"],
    ["meaning-entailing substitutability", "used for", "semantic-oriented NLP applications"],
    ["human agreement", "evaluate for", "meaning-entailing substitutability"],
    ["semantic criterion", "evaluate for", "distributional word feature vectors"],
    ["distributional word feature vectors", "used for", "word similarity"],
    ["measure", "evaluate for", "feature vector quality"],
    ["feature weighting and selection function", "used for", "feature vectors"],
    ["feature weighting and selection function", "used for", "word similarity"],
    ["feature vectors", "conjunction", "word similarity"]
]"""

# seed: 1105
# triples_gpt = [["We", "suggest", "goal"], ["We", "suggest", "evaluation criterion"], ["evaluation criterion", "new", "goal"], ["evaluation criterion", "fits", "needs"], ["evaluation criterion", "evaluated directly", "good level of human agreement"], ["We", "analyze", "quality"], ["quality", "impact on", "word similarity results"], ["We", "propose", "measure"], ["measure", "evaluating", "feature vector quality"], ["feature vector quality", "yield", "superior feature vectors"], ["feature vector quality", "yield", "better word similarity performance"], ["We", "present", "feature weighting function"], ["feature weighting function", "yields", "superior feature vectors"], ["We", "present", "selection function"], ["selection function", "yields", "superior feature vectors"]]

triples_we = [['evaluation criterion', 'related to', 'word similarity measures'], ['evaluation criterion', 'related to', 'meaning-entailing substitutability'], ['evaluation criterion', 'related to', 'semantic-oriented NLP applications'], ['evaluation criterion', 'assessed by', 'human agreement'], ['word similarity measures', 'quality assessed by', 'distributional word feature vectors'], ['distributional word feature vectors', 'impact on', 'word similarity results'], ['distributional word feature vectors', 'quality evaluated by', 'objective measure'], ['feature vectors', 'generated by', 'feature weighting and selection function'], ['feature vectors', 'enhances', 'word similarity performance']]


triples = triples_we
# 创建一个有向图
G = nx.DiGraph()

# 添加节点和边
for triple in triples:
    G.add_node(triple[0])
    G.add_node(triple[2])
    G.add_edge(triple[0], triple[2], relation=triple[1])
node_labels = {node: wrap_labels({node: node}, width=10)[node] for node in G.nodes()}
# 可视化图
plt.figure(figsize=(12, 12))
pos = nx.spring_layout(G, k=2, seed=1127)  # 为图布局
pos_higher = {}
for k, v in pos.items():
    pos_higher[k] = (v[0], v[1] + 1)  # 调整节点位置，使标签不遮挡
nx.draw(G, pos_higher, with_labels=True, labels=node_labels, node_color='skyblue', node_size=15000, edge_color='grey', font_size=18, font_weight='bold', arrows=True)
edge_labels = nx.get_edge_attributes(G, 'relation')
nx.draw_networkx_edge_labels(G, pos_higher, edge_labels=edge_labels, font_size=15)

plt.title("Knowledge Graph Visualization")
plt.savefig("./kg.jpg", transparent=True)